apiVersion: apps/v1
kind: Deployment
metadata:
  name: studynotion-frontend
  namespace: three-tier
  labels:
    role: studynotion-frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: studynotion-frontend
  template:
    metadata:
      labels:
        role: studynotion-frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: studynotion-frontend
        image: 992382706381.dkr.ecr.us-east-1.amazonaws.com/studynotion-frontend:2
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 3000
